# Generated by Django 4.2.7 on 2023-12-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_call_adress_company_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_industry',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
