# Generated by Django 4.2.7 on 2023-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='est_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
