# Generated by Django 4.2.7 on 2023-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_est_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='est_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
