# Generated by Django 4.2.7 on 2023-12-02 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_alter_company_est_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(default=5000)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('ideal_candidate', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('industry', models.CharField(blank=True, choices=[('Education', 'Education'), ('Agriculture', 'Agriculture'), ('Infrastructure', 'Infrastructure'), ('Engineering', 'Engineering'), ('IT & Tech', 'IT & Tech'), ('Engineering', 'Engineering'), ('Media', 'Media'), ('Business & Entrepreneurship', 'Business & Entrepreneurship'), ('Art', 'Art'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Logistics', 'Logistics'), ('Law', 'Law'), ('Other', 'Other')], max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('Ethiopia', 'Ethiopia'), ('Rwanda', 'Rwanda'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('South Africa', 'South Afrca'), ('Mauritius', 'Mauritius'), ('United States', 'United States'), ('Other', 'Other')], max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('job_env', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Full-Time Job', 'Full-Time Job'), ('Part-Time Job', 'Part-Time Job'), ('Full-Time Internship', 'Full-Time Internship'), ('Part-Time Internship', 'Part-Time Internship')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, choices=[('3-Months', '3-Months'), ('4-Months', '4-Months'), ('6-Months', '6-Months'), ('Contract', 'Contract')], max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
