# Generated by Django 4.2.7 on 2023-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_env_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
