# Generated by Django 4.2.7 on 2023-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, choices=[('3-Months', '3-Months'), ('4-Months', '4-Months'), ('6-Months', '6-Months'), ('Contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-Time Job', 'Full-Time Job'), ('Part-Time Job', 'Part-Time Job'), ('Full-Time Internship', 'Full-Time Internship'), ('Part-Time Internship', 'Part-Time Internship')], max_length=20, null=True),
        ),
    ]
